services:
  ml_service:
    build:
      context: ./ml_service
      dockerfile: Dockerfile
    image: mobile_classifier_model:2
    container_name: ml_service
    ports:
      - "8000:8000"
    volumes:
      - ../services/models:/models:z
    networks:
      - monitoring_network
    restart: unless-stopped

  requests:
    build:
      context: ./requests
      dockerfile: Dockerfile
    image: mobile_requests:1
    container_name: requests_service
    depends_on:
      - ml_service
    networks:
      - monitoring_network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning:z
    depends_on:
      - prometheus
    networks:
      - monitoring_network
    restart: unless-stopped

networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

