global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ml_service'
    static_configs:
      - targets: ['ml_service:8000']
        labels:
          service: 'mobile_classifier'

